export const REMOVE_TOAST = "REMOVE_TOAST";
export const CREATE_TOAST = "CREATE_TOAST";

export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const RECEIVE_POST = "RECEIVE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const RECEIVE_COMMENT = "RECEIVE_COMMENT";
export const MODIFY_COMMENT_SUCCESS = "MODIFY_COMMENT_SUCCESS";

export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
